### ISSUE TITLE
500 Internal Server Error on reload

### ISSUE THREAD

**Issue by proidit** [SaleCar/Vue3-QuickStart#4]
When you are inside the single page  http://domani01/subfolderapp/page3 and reload .. error

**Comment by SaleCar** [comment]
Hello,

You should check webserver logs to see what is error. 

By domain I would conclude that you put the application in a subfolder. This is not initially supported because then the routing is different. You'd have to mess with .htaccess to work that way.

**Comment by proidit** [comment]
ok tanks.

**Comment by proidit** [comment]
ok tanks. 
i use nginx.... 
unique solution : edit nginx domain config?

**Comment by SaleCar** [comment]
I don't know how to set it up. There is probably some option to set all requests within that folder to be treated as root applications. Or switch to a vue router.

**Comment by SaleCar** [comment]
Ovde imaš sličan projekat koji koristi vue router:

https://github.com/SaleCar/Quasar-UMD-Template

**Comment by SaleCar** [comment]
Here you have a similar project that uses a vue router:

https://github.com/SaleCar/Quasar-UMD-Template
