### ISSUE TITLE
CSS strategy?

### ISSUE THREAD

**Issue by winternet-studio** [SaleCar/Vue3-QuickStart#7]
Any ideas what would be the best approach to organizing page-specific and component-specific CSS code?

**Comment by SaleCar** [comment]
Well, there isn't much choice.

You can use html inline css or separate css files with links in index.html.

Vue does not allow style tags in components unless bundling is used.

**Comment by winternet-studio** [comment]
Yeah, I guess that's our only options... Then just organize the CSS with class names for each component or something...

One downside of not using bundling...!
